### ISSUE TITLE
Add the font B612 to Font Manager

### ISSUE THREAD

**Issue by StephenWassell** [androidacy/FontManager#1]
"B612 is an highly legible open source font family designed and tested to be used on aircraft cockpit screens."

That sounds like a perfect screen font! Could you add it to the tool please?

https://b612-font.com/

**Comment by androidacy** [comment]
Font has been added. Make sure to refresh your lists.

Thanks for the suggestion!

**Comment by StephenWassell** [comment]
Thanks for the quick response! There's something not quite right though: it replaced the Normal font, but Medium and Light are still the one I had installed before (Aleo).

**Comment by androidacy** [comment]
They don't seem to publish those variants, unfortunately.
