### ISSUE TITLE
Broken website

### ISSUE THREAD

**Issue by Qwerty-Space** [androidacy/FontManager#10]
Androidacy shows as a mobile site on desktop as well.

**Comment by androidacy** [comment]
Cannot reproduce and unless you have an extraordinarily small screen resolution this won't happen.

**Comment by Qwerty-Space** [comment]
> Cannot reproduce and unless you have an extraordinarily small screen resolution this won't happen.

Maybe I'm wrong, but I'm on a 1920x1080 screen, and all elements seem mobile-like, including the fact that there's a hamburger menu (that can't be closed).

Also the Font Previewer just straight up isn't working

**Comment by androidacy** [comment]
The hamburger menu doesn't change based on screen size, and I'm guessing that the fact it stays open either a) you're blocking JavaScript or b) you need to clear your browser cache.
