### ISSUE TITLE
Download issue in A12

### ISSUE THREAD

**Issue by ruhend** [androidacy/FontManager#5]
```
/data/adb/modules/fontrevival/tools/utils: line 46: exit : : numeric argument required
⚠️ Download failed! Bailing out!

⛔ ERROR ⛔ 
something bad happened and the script has encountered an issue
Make sure you're following instructions and try again!
⛔ ERROR ⛔ 
```

Device: Redmi Note 7
Android Version: Android 12 Beta 1
Module Version: v4.1.3

_Temporary fix (worked for me)_
_Install an android 11 rom, download the fonts, and copy them._
_Replace them in the sdcard/FontManager/font and sdcard/FontManager/emoji_
_And re-run the command in terminal_
_You will still get the error, but the font will be installed_

**Comment by androidacy** [comment]
Already fixed in current beta.

ALWAYS test latest beta/alpha before reporting bugs.

**Comment by ruhend** [comment]
Now I've updated my magisk module, and here is the output.
I've cross checked it on 4 other android 12 users, and our results were the same. 

```
Loading...
No internet access, or the API is down! Try again later!
The module will exit now, as it needs connectivity with the API to work.
```

Thanks for the module thou! Really appreciate your work! 😊
