### ISSUE TITLE
Doesn't change font on Asus Zenfone 6

### ISSUE THREAD

**Issue by waterlubber** [androidacy/FontManager#7]
I'm using an Asus Zenfone 6, and I don't think this is properly changing the font on my phone. *Emoji* conversion works perfectly, and emojis are correctly changed throughout the system (so I believe this is working fine). However, the font does not change in any other app (including Settings, Gboard and my messaging app, QKSMS.)

For example, here is a screenshot of Gboard. I have successfully changed the font (in this case) to B612, and rebooted my phone afterwards.
(note the small serifs on the "i" and "j" not present in the B612 font)
![Screenshot_20210610-230419567](https://user-images.githubusercontent.com/7517025/121624848-4b997d00-ca40-11eb-836e-cec1f3b9cff0.png)
Emoji work fine:
![Screenshot_20210610-230515584](https://user-images.githubusercontent.com/7517025/121624866-57853f00-ca40-11eb-9a9d-edf117165494.png)
The font appears to be stuck to the system one.
Any advice? I'm on Android 11 with Magisk 23.0 and v4.2.14 of Font Manager.

**Comment by androidacy** [comment]
I'm guessing ZenUI uses it's own custom fonts. Is there an option to force Roboto anywhere in the device settings?

**Comment by waterlubber** [comment]
Not that I can tell — only three fonts are offered and they're all unlabelled. 

If I find them in the system files, do you think I could just Magisk overwrite them with a new one?
![Screenshot_20210611-165129775](https://user-images.githubusercontent.com/7517025/121747348-476b6f00-cad5-11eb-8c28-199e44206cbd.png)

**Comment by androidacy** [comment]
Try each one. One should be Roboto

**Comment by waterlubber** [comment]
None of them are Roboto, for some strange reason. I wasn't able to identify the two right fonts, but the first option appears to be _Carrois Gothic_, and it's located in `/system/fonts/CarroisGothicSC-Regular.ttf`. I'm going to try writing a custom Magisk module to overwrite it. I'm not sure if this is worth special handling for ZenUI devices, or if the other two are also in `/system/fonts`. 

Here's a listing from `ls -hal /system/fonts`:
https://hastebin.com/raw/ipifusagow
